APP_NAME = "ReportIQ AI"
APP_DESCRIPTION = "Your AI-Powered Medical Report Analyzer"
APP_ICON = "🩺"
APP_TAGLINE = "Discover Smarter Health Insights with AI"

# App settings
MAX_UPLOAD_SIZE_MB = 20
MAX_PDF_PAGES = 50
SESSION_TIMEOUT_MINUTES = 30
ANALYSIS_DAILY_LIMIT = 15

# UI Settings
PRIMARY_COLOR = "#64B5F6"
SECONDARY_COLOR = "#1976D2"
